# Generated by Django 5.1.2 on 2024-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=15)),
                ('timestamp', models.CharField(max_length=50)),
                ('status_desc', models.CharField(max_length=100)),
                ('submit_date', models.CharField(max_length=50)),
                ('deliv_date', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
                ('retry', models.IntegerField()),
            ],
        ),
    ]
